version: '3.8'

services:
  dummy:
    container_name: nestjs-dummy
    image: nestjs-dummy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3400:3000
      - 9001:9001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

